Repository GAA-UAM/scikit-fda, pull requests merged in 2019-03, with the labels that each got.

#59 Basis domain check
  fda/basis.py
Labels: enhancement

#58 Fixed basis properties that not exists
  fda/basis.py
Labels: bug

#56 Plot function of FDataGrid moved to FData
  examples/plot_composition.py
  examples/plot_extrapolation.py
  examples/plot_interpolation.py
  examples/plot_landmark_registration.py
  examples/plot_landmark_shift.py
  fda/basis.py
  fda/functional_data.py
  fda/grid.py
Labels: question

#61 Times function por fdatabasis multiplication
  fda/basis.py
  tests/test_basis.py
Labels: enhancement
